version: '3.1'


volumes:
  wordpress:
  database:
services:
  wordpress:
    depends_on: 
      - db
    image: wordpress
    restart: always
    ports:
      - "8080:90"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: password123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - database:/var/lib/mysql
